### ISSUE TITLE
Not a supported wheel on this platform.

### ISSUE THREAD

**Issue by faaip** [radimspetlik/pytorch_rpi_builds#1]
Hi Radim, thank you for these wheels!

Tried building on a raspberry pi 4 with python 3.8.5 using the following command:
`
pip3 install https://github.com/radimspetlik/pytorch_rpi_builds/blob/master/torch-1.6.0a0%2B9d7a79a-cp37-cp37m-linux_armv7l.whl
`
I do however get the following error:
`
ERROR: torch-1.6.0a0+9d7a79a-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.
`

What did you do to get past that?

**Comment by radimspetlik** [comment]
Hey!

The 1.6.0 version is not working (it is an alpha version built by accident). However, the 1.5.0 version is OK...

The plan is to (eventually) build the 1.6.0. Would you fancy @faaip, you could build it and we can publish it here.

Sorry for that...

**Comment by faaip** [comment]
Done! I created a pull request. #2
